### ISSUE TITLE
Error in loadNamespace

### ISSUE THREAD

**Issue by Emzarally** [vosonlab/SocialMediaLab#18]
Hi - when attempting to install.packages("SocialMediaLab") I get the following error. I've tried changing libPaths, and re-installing R and R-Studio. Appreciate if anyone can guide me in the direction of a solution. 

Loading required package: SocialMediaLab
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Rcpp

Cheerio
em

**Comment by rjackland** [comment]
This was resolved, and not related to bug.  Closing.
