### ISSUE TITLE
Facebook collection - no posts found

### ISSUE THREAD

**Issue by vosonlab** [vosonlab/SocialMediaLab#28]
The following test Facebook collection that we use in SocialMediaLab teaching materials (see e.g. [here](http://vosonlab.net/big-data-analysis-ACSPRI-Summer2017)) is failing:
 
g_bimodal_facebook_csg <- Authenticate("Facebook", 
  appID = appID, appSecret = appSecret) %>% 
  SaveCredential("FBCredential.RDS") %>%
  Collect(pageName="StopCoalSeamGasBlueMountains", rangeFrom="2015-06-23", 
  rangeTo="2015-07-23", writeToFile=TRUE) %>% 
  Create("Bimodal")

It iterates through the days (as per normal) but then fails with:

Error. No posts found for this date range! Please try a larger range.Error. Cannot create bimodal network using this type of data (see help file for data types and sources).
Error in class(networkToReturn) <- append(class(networkToReturn), c("SocialMediaLab")) : 
  attempt to set an attribute on NULL

Another user has reported similar problem.

This is using SocialMediaLab_0.23.0 and Rfacebook_0.6.11 (both current versions).

There may have been change in Facebook API?

**Comment by vosonlab** [comment]
This was just tested with SocialMediaLab_0.23.0 (CRAN version) and latest CRAN version of Rfacebook (0.6.15 - published 2017-05-25) and it now works. So it seems that there might have been a change to Facebook API regarding authentication which broke Rfacebook and it has been fixed in the latest version.

**Comment by timothyjgraham** [comment]
I am closing this issue as it appears to be solved.

**Comment by MVATFM** [comment]
Sorry but I have the same issue and It doesnt work for me, even with this version. How can I solve it?

**Comment by rjackland** [comment]
Please see #29 - unfortunately, changes to the Facebook API mean that we can't collect data from FB fan pages any more.
  
Also please note that SocialMediaLab has been renamed [vosonSML](https://github.com/vosonlab/vosonSML) (which is now on CRAN) and so SocialMediaLab will no longer be developed.
